global:
  scrape_interval: 10s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'springbootapp_metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springbootapp:8080']
        labels:
          group: 'springboot'
    basic_auth:
      username: admin
      password: Roman@123

  - job_name: 'opentelemetry-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['opentelemetry-collector:8889']
